name: example
description: Demonstrates how to use the fl_mlkit_text_recognize plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  camera: ^0.9.2+2
  fl_mlkit_text_recognize:
    git:
      url: https://github.com/chocosongsonii/fl_mlkit_text_recognize
      ref: main
  flutter:
    sdk: flutter
  flutter_curiosity: ^3.3.0
  flutter_waya: ^1.13.1
  permission_handler: ^8.1.4+2

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
